quarkus.http.port=9090

# OIDC (Keycloak)
quarkus.oidc.client-id=login-keycloak
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.roles.role-claim-path=realm_access/roles,resource_access/login-keycloak/roles
quarkus.oidc.token.issuer=any
quarkus.oidc.authentication.scopes=openid,roles

# Perfil browser
%web.quarkus.oidc.application-type=web-app

# Perfil api
%api.quarkus.oidc.application-type=service

# Perfil dev (executando na máquina local)
%dev.quarkus.oidc.auth-server-url=http://localhost:8080/realms/redhat-dev

# Dev Services Keycloak
%dev.quarkus.devservices.enabled=false

# Perfil docker
%docker.quarkus.oidc.auth-server-url=http://keycloak:8080/realms/redhat-dev
%docker.quarkus.oidc.application-type=service
%docker.quarkus.oidc.token.issuer=any
