quarkus.http.port=9090

# OIDC (Keycloak) - comum a todos os perfis
quarkus.oidc.auth-server-url=http://localhost:8080/realms/redhat-dev
quarkus.oidc.client-id=login-keycloak
quarkus.oidc.credentials.secret=wTynbek6fLZLJjWD3G08cgSN6A7hca1r
quarkus.oidc.roles.role-claim-path=realm_access/roles
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.authentication.scopes=openid,roles

# Perfil browser
%web.quarkus.oidc.application-type=web-app

# Perfil api
%api.quarkus.oidc.application-type=service


# Dev Services Keycloak
%dev.quarkus.devservices.enabled=false
